// lib/constants.ts
import {
    Search,
    MessageCircle,
    Star,
    BookOpen,
    UserPlus,
    Store,
    Coins,
    Crown,
    ShieldCheck,
    Headphones,
    Trash2,
    Camera,
  } from 'lucide-react';
  import type { GuideSection } from './types';
  
  // ========== COLORES DE ACENTO PARA EL MANUAL ==========
  export const MANUAL_ACCENT = {
    blue:   { bg: 'bg-blue-500/10',   text: 'text-blue-400',      border: 'border-blue-500/20', dot: 'bg-blue-400' },
    orange: { bg: 'bg-primary/10',    text: 'text-primary-light', border: 'border-primary/20',  dot: 'bg-primary-light' },
    purple: { bg: 'bg-purple-500/10', text: 'text-purple-400',    border: 'border-purple-500/20', dot: 'bg-purple-400' },
    amber:  { bg: 'bg-amber/10',      text: 'text-amber',         border: 'border-amber/20',    dot: 'bg-amber' },
    green:  { bg: 'bg-accent/10',     text: 'text-accent',        border: 'border-accent/20',   dot: 'bg-accent' },
    rose:   { bg: 'bg-rose-500/10',   text: 'text-rose-400',      border: 'border-rose-500/20', dot: 'bg-rose-400' },
  } as const;
  
  // ========== SECCIONES DEL MANUAL ==========
  export const GUIDE_SECTIONS: GuideSection[] = [
    {
      id: 'cliente',
      title: 'Soy Cliente — Buscar y contratar',
      icon: Search,
      accent: 'blue',
      content: [
        {
          title: 'Explora profesionales por categoría',
          desc: 'En la pantalla principal, usa los filtros de categoría, ubicación y rating para encontrar al profesional ideal.',
          icon: Search,
          accent: 'blue',
          screenshot: 'servicios.jpeg',
          subSteps: [
            'Selecciona una categoría (electricista, gasfitero, chef, etc.)',
            'Filtra por departamento, provincia y distrito',
            'Ordena por rating o por plan (Premium primero)',
          ],
        },
        {
          title: 'Contacta directamente',
          desc: 'Cada tarjeta muestra WhatsApp y teléfono. Toca el botón verde para iniciar una conversación.',
          icon: MessageCircle,
          accent: 'green',
          screenshot: 'Tarjeta de proveedor con botones de WhatsApp y teléfono',
          subSteps: [
            'Toca el ícono de WhatsApp para enviar un mensaje',
            'Toca el ícono de teléfono para llamar directamente',
            'También puedes ver la ubicación en el mapa',
          ],
        },
        {
          title: 'Califica el servicio',
          desc: 'Después del servicio, deja una reseña con estrellas, comentario y foto.',
          icon: Star,
          accent: 'amber',
          screenshot: 'Formulario de reseña con estrellas, comentario y foto',
          subSteps: [
            'Toca "Escribir reseña" en el perfil del proveedor',
            'Califica de 1 a 5 estrellas',
            'Añade un comentario y una foto (opcional)',
            'Tu reseña queda geolocalizada con GPS',
          ],
        },
      ],
    },
    {
      id: 'profesional',
      title: 'Soy Profesional Independiente',
      icon: UserPlus,
      accent: 'orange',
      content: [
        {
          title: 'Regístrate como Profesional',
          desc: 'Llena el formulario con DNI, teléfono, categoría, ubicación y fotos de tus trabajos.',
          icon: UserPlus,
          accent: 'orange',
          screenshot: 'Formulario de registro de profesional independiente',
          subSteps: [
            'Elige un nombre para tu servicio',
            'Ingresa tu DNI (8 dígitos)',
            'Selecciona categoría y subcategoría',
            'Establece tu ubicación',
            'Sube fotos de tus trabajos anteriores',
          ],
          links: [
            { label: 'Descargar la app', href: '#' },
            { label: 'Ir al panel web', href: '/login' },
          ],
        },
        {
          title: 'Configura tu perfil',
          desc: 'Edita información, añade servicios, redes sociales y horarios de atención.',
          icon: Camera,
          accent: 'orange',
          screenshot: 'Panel de edición de perfil profesional',
          subSteps: [
            'Ve a "Perfil" en tu panel',
            'Añade una descripción detallada',
            'Configura tu horario por días',
            'Añade tus redes sociales',
            'Cambia tu disponibilidad',
          ],
        },
        {
          title: 'Gestiona tus servicios',
          desc: 'Añade los servicios que ofreces según tu plan contratado.',
          icon: BookOpen,
          accent: 'orange',
          screenshot: 'Lista de servicios con botón para añadir nuevo',
          subSteps: [
            'Toca "Añadir servicio"',
            'Escribe nombre y descripción',
            'Guarda y repite para cada servicio',
            'Considera subir de plan si llegas al límite',
          ],
        },
      ],
    },
    {
      id: 'negocio',
      title: 'Tengo un Negocio',
      icon: Store,
      accent: 'purple',
      content: [
        {
          title: 'Registra tu Negocio',
          desc: 'Ingresa RUC, Nombre Comercial, Razón Social y configura opciones de delivery.',
          icon: Store,
          accent: 'purple',
          screenshot: 'Formulario de registro de negocio con campos RUC y delivery',
          subSteps: [
            'Ingresa el RUC de tu negocio (11 dígitos)',
            'Escribe tu Nombre Comercial',
            'Escribe tu Razón Social (registro SUNAT)',
            'Activa el toggle de Delivery si realizas envíos',
            'Si tienes delivery, activa "Coordinación full" si aplica',
          ],
          links: [
            { label: 'Descargar la app', href: '#' },
            { label: 'Ir al panel web', href: '/login' },
          ],
        },
        {
          title: 'Añade productos',
          desc: 'Agrega los productos que vendes con su precio en soles (S/.).',
          icon: BookOpen,
          accent: 'purple',
          screenshot: 'Lista de productos con precios y botón para añadir',
          subSteps: [
            'Ve a "Productos" en tu panel',
            'Toca "Añadir producto"',
            'Escribe nombre, descripción y precio en S/.',
            'El precio se mostrará en tu tarjeta pública',
          ],
        },
      ],
    },
    {
      id: 'monedas',
      title: 'Sistema de Monedas y Referidos',
      icon: Coins,
      accent: 'amber',
      content: [
        {
          title: 'Consigue tu código de referido',
          desc: 'Cada usuario tiene un código único. Compártelo y gana monedas.',
          icon: Coins,
          accent: 'amber',
          screenshot: 'Sección de promociones con código de referido',
          subSteps: [
            'Ve a "Promociones" desde tu perfil o panel',
            'Copia tu código personal o comparte el enlace',
            'Recibes 25 monedas por cada registro aprobado',
            'Tu amigo recibe 5 monedas de bienvenida',
          ],
        },
        {
          title: 'Canjea tus monedas',
          desc: 'Acumula monedas y canjéalas por planes gratis o servicios reales.',
          icon: Crown,
          accent: 'amber',
          screenshot: 'Pantalla de canje de monedas con opciones disponibles',
          subSteps: [
            '1000 monedas = Plan Estándar por 1 mes',
            '2000 monedas = Plan Premium por 2 meses',
            'También puedes canjear por servicios reales',
            'Ve a "Canjear monedas" para ver las opciones',
          ],
        },
      ],
    },
    {
      id: 'planes',
      title: 'Planes y Suscripciones',
      icon: Crown,
      accent: 'orange',
      content: [
        {
          title: 'Planes disponibles',
          desc: 'Servi ofrece 3 planes: Gratis, Estándar y Premium.',
          icon: Crown,
          accent: 'orange',
          screenshot: 'Comparativa de planes Gratis, Estándar y Premium',
          subSteps: [
            'Gratis: 3 servicios/productos, 3 fotos',
            'Estándar: 6 servicios/productos, 6 fotos, estadísticas',
            'Premium: ilimitado, máxima visibilidad, estadísticas avanzadas',
          ],
          links: [{ label: 'Ver planes en panel web', href: '/login' }],
        },
        {
          title: 'Cómo pagar con Yape',
          desc: 'Escanea el QR, sube tu comprobante y un código de verificación.',
          icon: Coins,
          accent: 'orange',
          screenshot: 'Pantalla de pago con QR de Yape y campos de comprobante',
          subSteps: [
            'Ve a "Ajustes" > "Ver planes disponibles"',
            'Elige Estándar o Premium y toca "Adquirir"',
            'Escanea el QR con Yape y paga el monto exacto',
            'Sube captura del comprobante',
            'Ingresa el código de verificación de 3 dígitos',
            'El admin revisará y activará tu plan',
          ],
        },
        {
          title: 'Cancelar un plan',
          desc: 'Puedes cancelar tu plan activo desde Ajustes cuando lo desees.',
          icon: Trash2,
          accent: 'rose',
          screenshot: 'Sección de suscripción con botón de cancelar plan',
          subSteps: [
            'Ve a "Ajustes" en tu panel',
            'En suscripción, toca "Cancelar plan"',
            'Confirma la cancelación',
            'Tu plan pasará a estado cancelado',
          ],
        },
      ],
    },
    {
      id: 'cuenta',
      title: 'Gestión de Cuenta',
      icon: ShieldCheck,
      accent: 'green',
      content: [
        {
          title: 'Cambiar contraseña',
          desc: 'Actualiza tu contraseña desde la sección de Perfil.',
          icon: ShieldCheck,
          accent: 'green',
          screenshot: 'Formulario de cambio de contraseña',
          subSteps: [
            'Ve a "Perfil" > "Cambiar contraseña"',
            'Ingresa tu contraseña actual',
            'Ingresa la nueva contraseña y confírmala',
            'Guarda los cambios',
          ],
        },
        {
          title: 'Eliminar cuenta',
          desc: 'Elimina permanentemente tu cuenta y todos tus datos.',
          icon: Trash2,
          accent: 'rose',
          screenshot: 'Pantalla de confirmación para eliminar cuenta',
          subSteps: [
            'Ve a "Perfil" > "Eliminar cuenta"',
            'Lee la advertencia (acción irreversible)',
            'Escribe "ELIMINAR" para confirmar',
            'Toca "Eliminar cuenta"',
            'Todos tus datos serán borrados',
          ],
        },
        {
          title: 'Reportar un problema',
          desc: 'Reporta bugs, sugerencias o problemas con algún proveedor.',
          icon: Headphones,
          accent: 'green',
          screenshot: 'Formulario de reporte de problemas',
          subSteps: [
            'En tu perfil: "Reportar un problema"',
            'Describe el inconveniente y envía',
            'Panel profesional: "Ajustes" > "Reportar problema"',
            'También puedes escribir a soporte',
          ],
          links: [{ label: 'Soporte técnico', href: 'mailto:soporteofiapp@gmail.com' }],
        },
      ],
    },
  ];