-- Desactivar localidades SEED antiguas
UPDATE localities SET "isActive" = false WHERE "source" = 'SEED';

-- Insertar nuevas localidades (solo si no existen)
INSERT INTO localities (name, department, province, district, country, source, "isActive", "createdAt")
VALUES
  ('Huancayo', 'Junín', 'Huancayo', 'Huancayo', 'Perú', 'SEED', true, NOW()),
  ('El Tambo', 'Junín', 'Huancayo', 'El Tambo', 'Perú', 'SEED', true, NOW()),
  ('Chilca', 'Junín', 'Huancayo', 'Chilca', 'Perú', 'SEED', true, NOW()),
  ('Pilcomayo', 'Junín', 'Huancayo', 'Pilcomayo', 'Perú', 'SEED', true, NOW()),
  ('Sapallanga', 'Junín', 'Huancayo', 'Sapallanga', 'Perú', 'SEED', true, NOW()),
  ('Jauja', 'Junín', 'Jauja', 'Jauja', 'Perú', 'SEED', true, NOW()),
  ('Concepción', 'Junín', 'Concepción', 'Concepción', 'Perú', 'SEED', true, NOW()),
  ('Matahuasi', 'Junín', 'Concepción', 'Matahuasi', 'Perú', 'SEED', true, NOW()),
  ('Santa Rosa de Ocopa', 'Junín', 'Concepción', 'Santa Rosa de Ocopa', 'Perú', 'SEED', true, NOW()),
  ('Chupaca', 'Junín', 'Chupaca', 'Chupaca', 'Perú', 'SEED', true, NOW()),
  ('Yanacancha', 'Junín', 'Chupaca', 'Yanacancha', 'Perú', 'SEED', true, NOW()),
  ('Tarma', 'Junín', 'Tarma', 'Tarma', 'Perú', 'SEED', true, NOW()),
  ('La Merced', 'Junín', 'Chanchamayo', 'La Merced', 'Perú', 'SEED', true, NOW()),
  ('Pichanaqui', 'Junín', 'Chanchamayo', 'Pichanaqui', 'Perú', 'SEED', true, NOW()),
  ('Satipo', 'Junín', 'Satipo', 'Satipo', 'Perú', 'SEED', true, NOW()),
  ('Mazamari', 'Junín', 'Satipo', 'Mazamari', 'Perú', 'SEED', true, NOW()),
  ('Pangoa', 'Junín', 'Satipo', 'Pangoa', 'Perú', 'SEED', true, NOW()),
  ('La Oroya', 'Junín', 'Yauli', 'La Oroya', 'Perú', 'SEED', true, NOW()),
  ('Cercado de Lima', 'Lima', 'Lima', 'Cercado de Lima', 'Perú', 'SEED', true, NOW()),
  ('Miraflores', 'Lima', 'Lima', 'Miraflores', 'Perú', 'SEED', true, NOW()),
  ('San Isidro', 'Lima', 'Lima', 'San Isidro', 'Perú', 'SEED', true, NOW()),
  ('Barranco', 'Lima', 'Lima', 'Barranco', 'Perú', 'SEED', true, NOW()),
  ('Santiago de Surco', 'Lima', 'Lima', 'Santiago de Surco', 'Perú', 'SEED', true, NOW()),
  ('La Molina', 'Lima', 'Lima', 'La Molina', 'Perú', 'SEED', true, NOW()),
  ('San Borja', 'Lima', 'Lima', 'San Borja', 'Perú', 'SEED', true, NOW()),
  ('Jesús María', 'Lima', 'Lima', 'Jesús María', 'Perú', 'SEED', true, NOW()),
  ('Lince', 'Lima', 'Lima', 'Lince', 'Perú', 'SEED', true, NOW()),
  ('Magdalena del Mar', 'Lima', 'Lima', 'Magdalena del Mar', 'Perú', 'SEED', true, NOW()),
  ('Pueblo Libre', 'Lima', 'Lima', 'Pueblo Libre', 'Perú', 'SEED', true, NOW()),
  ('San Miguel', 'Lima', 'Lima', 'San Miguel', 'Perú', 'SEED', true, NOW()),
  ('Breña', 'Lima', 'Lima', 'Breña', 'Perú', 'SEED', true, NOW()),
  ('La Victoria', 'Lima', 'Lima', 'La Victoria', 'Perú', 'SEED', true, NOW()),
  ('Rímac', 'Lima', 'Lima', 'Rímac', 'Perú', 'SEED', true, NOW()),
  ('San Juan de Lurigancho', 'Lima', 'Lima', 'San Juan de Lurigancho', 'Perú', 'SEED', true, NOW()),
  ('San Martín de Porres', 'Lima', 'Lima', 'San Martín de Porres', 'Perú', 'SEED', true, NOW()),
  ('Comas', 'Lima', 'Lima', 'Comas', 'Perú', 'SEED', true, NOW()),
  ('Los Olivos', 'Lima', 'Lima', 'Los Olivos', 'Perú', 'SEED', true, NOW()),
  ('San Vicente de Cañete', 'Lima', 'Cañete', 'San Vicente de Cañete', 'Perú', 'SEED', true, NOW()),
  ('Huaral', 'Lima', 'Huaral', 'Huaral', 'Perú', 'SEED', true, NOW()),
  ('Chancay', 'Lima', 'Huaral', 'Chancay', 'Perú', 'SEED', true, NOW()),
  ('Huacho', 'Lima', 'Huaura', 'Huacho', 'Perú', 'SEED', true, NOW()),
  ('Barranca', 'Lima', 'Barranca', 'Barranca', 'Perú', 'SEED', true, NOW()),
  ('Callao', 'Callao', 'Callao', 'Callao', 'Perú', 'SEED', true, NOW()),
  ('Bellavista', 'Callao', 'Callao', 'Bellavista', 'Perú', 'SEED', true, NOW()),
  ('La Perla', 'Callao', 'Callao', 'La Perla', 'Perú', 'SEED', true, NOW()),
  ('La Punta', 'Callao', 'Callao', 'La Punta', 'Perú', 'SEED', true, NOW()),
  ('Carmen de la Legua Reynoso', 'Callao', 'Callao', 'Carmen de la Legua Reynoso', 'Perú', 'SEED', true, NOW()),
  ('Ventanilla', 'Callao', 'Callao', 'Ventanilla', 'Perú', 'SEED', true, NOW()),
  ('Mi Perú', 'Callao', 'Callao', 'Mi Perú', 'Perú', 'SEED', true, NOW()),
  ('Ayacucho', 'Ayacucho', 'Huamanga', 'Ayacucho', 'Perú', 'SEED', true, NOW()),
  ('Carmen Alto', 'Ayacucho', 'Huamanga', 'Carmen Alto', 'Perú', 'SEED', true, NOW()),
  ('San Juan Bautista', 'Ayacucho', 'Huamanga', 'San Juan Bautista', 'Perú', 'SEED', true, NOW()),
  ('Jesús Nazareno', 'Ayacucho', 'Huamanga', 'Jesús Nazareno', 'Perú', 'SEED', true, NOW()),
  ('Huanta', 'Ayacucho', 'Huanta', 'Huanta', 'Perú', 'SEED', true, NOW()),
  ('Luricocha', 'Ayacucho', 'Huanta', 'Luricocha', 'Perú', 'SEED', true, NOW()),
  ('Sivia', 'Ayacucho', 'Huanta', 'Sivia', 'Perú', 'SEED', true, NOW()),
  ('Cusco', 'Cusco', 'Cusco', 'Cusco', 'Perú', 'SEED', true, NOW()),
  ('San Jerónimo', 'Cusco', 'Cusco', 'San Jerónimo', 'Perú', 'SEED', true, NOW()),
  ('San Sebastián', 'Cusco', 'Cusco', 'San Sebastián', 'Perú', 'SEED', true, NOW()),
  ('Wanchaq', 'Cusco', 'Cusco', 'Wanchaq', 'Perú', 'SEED', true, NOW()),
  ('Santiago', 'Cusco', 'Cusco', 'Santiago', 'Perú', 'SEED', true, NOW()),
  ('Urubamba', 'Cusco', 'Urubamba', 'Urubamba', 'Perú', 'SEED', true, NOW()),
  ('Machu Picchu', 'Cusco', 'Urubamba', 'Machu Picchu', 'Perú', 'SEED', true, NOW()),
  ('Ollantaytambo', 'Cusco', 'Urubamba', 'Ollantaytambo', 'Perú', 'SEED', true, NOW()),
  ('Calca', 'Cusco', 'Calca', 'Calca', 'Perú', 'SEED', true, NOW()),
  ('Pisac', 'Cusco', 'Calca', 'Pisac', 'Perú', 'SEED', true, NOW()),
  ('Anta', 'Cusco', 'Anta', 'Anta', 'Perú', 'SEED', true, NOW()),
  ('Sicuani', 'Cusco', 'Canchis', 'Sicuani', 'Perú', 'SEED', true, NOW()),
  ('Arequipa', 'Arequipa', 'Arequipa', 'Arequipa', 'Perú', 'SEED', true, NOW()),
  ('Yanahuara', 'Arequipa', 'Arequipa', 'Yanahuara', 'Perú', 'SEED', true, NOW()),
  ('Cayma', 'Arequipa', 'Arequipa', 'Cayma', 'Perú', 'SEED', true, NOW()),
  ('Cerro Colorado', 'Arequipa', 'Arequipa', 'Cerro Colorado', 'Perú', 'SEED', true, NOW()),
  ('Jacobo Hunter', 'Arequipa', 'Arequipa', 'Jacobo Hunter', 'Perú', 'SEED', true, NOW()),
  ('Mariano Melgar', 'Arequipa', 'Arequipa', 'Mariano Melgar', 'Perú', 'SEED', true, NOW()),
  ('Paucarpata', 'Arequipa', 'Arequipa', 'Paucarpata', 'Perú', 'SEED', true, NOW()),
  ('Socabaya', 'Arequipa', 'Arequipa', 'Socabaya', 'Perú', 'SEED', true, NOW()),
  ('José Luis Bustamante y Rivero', 'Arequipa', 'Arequipa', 'José Luis Bustamante y Rivero', 'Perú', 'SEED', true, NOW()),
  ('Alto Selva Alegre', 'Arequipa', 'Arequipa', 'Alto Selva Alegre', 'Perú', 'SEED', true, NOW()),
  ('Trujillo', 'La Libertad', 'Trujillo', 'Trujillo', 'Perú', 'SEED', true, NOW()),
  ('El Porvenir', 'La Libertad', 'Trujillo', 'El Porvenir', 'Perú', 'SEED', true, NOW()),
  ('Huanchaco', 'La Libertad', 'Trujillo', 'Huanchaco', 'Perú', 'SEED', true, NOW()),
  ('La Esperanza', 'La Libertad', 'Trujillo', 'La Esperanza', 'Perú', 'SEED', true, NOW()),
  ('Víctor Larco Herrera', 'La Libertad', 'Trujillo', 'Víctor Larco Herrera', 'Perú', 'SEED', true, NOW()),
  ('Pacasmayo', 'La Libertad', 'Pacasmayo', 'Pacasmayo', 'Perú', 'SEED', true, NOW()),
  ('Huamachuco', 'La Libertad', 'Sánchez Carrión', 'Huamachuco', 'Perú', 'SEED', true, NOW())
ON CONFLICT (department, province, district) 
DO UPDATE SET "isActive" = true, "source" = 'SEED', name = EXCLUDED.name;